Site\FrontEndBundle\Entity\Post:
    type: entity
    table: post
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        preview:
            type: string
            length: '500'
        content:
            type: text
        created:
            type: datetime
        slug:
            type: string
            length: 255
    manyToMany:
        tags:
            targetEntity: Tags
            inversedBy: posts
            joinTable:
                name: posts_tags
                joinColumns:
                    post_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }

            