site_front_end_homepage:
    path:     /hello/{name}
    defaults: { _controller: SiteFrontEndBundle:Main:index }
    
main_page:
    path: /{page}
    defaults: { _controller: SiteFrontEndBundle:News:main, page:1 }
    requirements: 
        page: \d+

post_by_slug:
    path: /post/{slug}
    defaults: { _controller: SiteFrontEndBundle:News:post }
        
posts_by_tag:
    path: /posts/tags/{slug}/{page}
    defaults: { _controller: SiteFrontEndBundle:News:postsByTag, page:1 }
    requirements: 
        page: \d+

posts_by_cat:
    path: /posts/category/{slug}/{page}
    defaults: { _controller: SiteFrontEndBundle:News:postsByCat, page:1}
    requirements:
        page: \d+
        
data:
    path: /data
    defaults: { _controller: SiteFrontEndBundle:Main:data }
    
about_page:
    path: /about
    defaults: { _controller: SiteFrontEndBundle:Main:about }
    
training_page:
    path: /training
    defaults: { _controller: SiteFrontEndBundle:Main:training }

gallery_page:
    path: /gallery
    defaults: { _controller: SiteFrontEndBundle:Main:gallery }
   
contacts_page:
    path: /contacts
    defaults: { _controller: SiteFrontEndBundle:Main:contacts }