site_front_end_homepage:
    path:     /hello/{name}
    defaults: { _controller: SiteFrontEndBundle:Main:index }
    
main_page:
    path: /{page}
    defaults: { _controller: SiteFrontEndBundle:News:main,page:1 }
    requirements: 
        page: \d+

posts_by_slug:
    path: /posts/{slug}
    defaults: { _controller: SiteFrontEndBundle:News:posts }
    
tags_by_slug:
    path: /posts/tags/{slug}
    defaults: { _controller: SiteFrontEndBundle:News:tagsBySlug }
    
about_page:
    path: /about
    defaults: { _controller: SiteFrontEndBundle:Main:about }
    
training_page:
    path: /training
    defaults: { _controller: SiteFrontEndBundle:Main:training }

gallery_page:
    path: /gallery
    defaults: { _controller: SiteFrontEndBundle:Main:gallery }
   
contacts_page:
    path: /contacts
    defaults: { _controller: SiteFrontEndBundle:Main:contacts }
    
