<?php

namespace Site\FrontEndBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function counter()
    {
        $qb=  $this->createQueryBuilder('p');
        $qb->select('COUNT(p.id)');
        return $qb->getQuery()->getSingleScalarResult();
        
    }
}
